/* ANSI-C code produced by gperf version 3.1 */
/* Command-line: /nix/store/mh4imb6grvya4zghn7qf0c4dpxa8g3pp-gperf-3.1/bin/gperf -L ANSI-C -t -N keyboard_lookup_key -H hash_key_name -p -C  */
/* Computed positions: -k'1-3,6,11,16,$' */

#if !((' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) \
      && ('%' == 37) && ('&' == 38) && ('\'' == 39) && ('(' == 40) \
      && (')' == 41) && ('*' == 42) && ('+' == 43) && (',' == 44) \
      && ('-' == 45) && ('.' == 46) && ('/' == 47) && ('0' == 48) \
      && ('1' == 49) && ('2' == 50) && ('3' == 51) && ('4' == 52) \
      && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) \
      && ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) \
      && ('=' == 61) && ('>' == 62) && ('?' == 63) && ('A' == 65) \
      && ('B' == 66) && ('C' == 67) && ('D' == 68) && ('E' == 69) \
      && ('F' == 70) && ('G' == 71) && ('H' == 72) && ('I' == 73) \
      && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) \
      && ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) \
      && ('R' == 82) && ('S' == 83) && ('T' == 84) && ('U' == 85) \
      && ('V' == 86) && ('W' == 87) && ('X' == 88) && ('Y' == 89) \
      && ('Z' == 90) && ('[' == 91) && ('\\' == 92) && (']' == 93) \
      && ('^' == 94) && ('_' == 95) && ('a' == 97) && ('b' == 98) \
      && ('c' == 99) && ('d' == 100) && ('e' == 101) && ('f' == 102) \
      && ('g' == 103) && ('h' == 104) && ('i' == 105) && ('j' == 106) \
      && ('k' == 107) && ('l' == 108) && ('m' == 109) && ('n' == 110) \
      && ('o' == 111) && ('p' == 112) && ('q' == 113) && ('r' == 114) \
      && ('s' == 115) && ('t' == 116) && ('u' == 117) && ('v' == 118) \
      && ('w' == 119) && ('x' == 120) && ('y' == 121) && ('z' == 122) \
      && ('{' == 123) && ('|' == 124) && ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
#error "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gperf@gnu.org>."
#endif

struct key { const char* name; unsigned short id; };

#define TOTAL_KEYWORDS 505
#define MIN_WORD_LENGTH 1
#define MAX_WORD_LENGTH 24
#define MIN_HASH_VALUE 1
#define MAX_HASH_VALUE 1962
/* maximum key range = 1962, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
hash_key_name (register const char *str, register size_t len)
{
  static const unsigned short asso_values[] =
    {
      1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963,
      1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963,
      1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963,
      1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963,
      1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963,    8,   85,
       245,  320,  335,  340,  408,  160,  190,  315,  358,   15,
        10,    0,    5,    0,    0,   10, 1963, 1963, 1963, 1963,
      1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963,
      1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963,
      1963, 1963, 1963, 1963, 1963,   15,  443,   40,  325,   55,
        30,   15,  305,  205,  290,   45,  470,  285,   60,   20,
         5,   10,   80,  159,  195,   50,  100,    0,  275,  350,
       475,  435,  338,  310,  468,   10,   35,    0,    0, 1963,
      1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963,
      1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963,
      1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963,
      1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963,
      1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963,
      1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963,
      1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963,
      1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963,
      1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963,
      1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963,
      1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963,
      1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963,
      1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963, 1963,
      1963, 1963, 1963, 1963
    };
  register unsigned int hval = len;

  switch (hval)
    {
      default:
        hval += asso_values[(unsigned char)str[15]];
      /*FALLTHROUGH*/
      case 15:
      case 14:
      case 13:
      case 12:
      case 11:
        hval += asso_values[(unsigned char)str[10]];
      /*FALLTHROUGH*/
      case 10:
      case 9:
      case 8:
      case 7:
      case 6:
        hval += asso_values[(unsigned char)str[5]+8];
      /*FALLTHROUGH*/
      case 5:
      case 4:
      case 3:
        hval += asso_values[(unsigned char)str[2]+1];
      /*FALLTHROUGH*/
      case 2:
        hval += asso_values[(unsigned char)str[1]];
      /*FALLTHROUGH*/
      case 1:
        hval += asso_values[(unsigned char)str[0]];
        break;
    }
  return hval + asso_values[(unsigned char)str[len - 1]];
}

const struct key *
keyboard_lookup_key (register const char *str, register size_t len)
{
  static const struct key wordlist[] =
    {
      {(char*)0},
      {"u", KEY_U},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"n", KEY_N},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"0", KEY_0},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"o", KEY_O},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"e", KEY_E},
      {(char*)0}, {(char*)0},
      {"undo", KEY_UNDO},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"mute", KEY_MUTE},
      {(char*)0},
      {"m", KEY_M},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"menu", KEY_MENU},
      {(char*)0},
      {"unmute", KEY_UNMUTE},
      {(char*)0}, {(char*)0},
      {"memo", KEY_MEMO},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0},
      {"d", KEY_D},
      {(char*)0}, {(char*)0},
      {"mode", KEY_MODE},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"end", KEY_END},
      {(char*)0},
      {"audio", KEY_AUDIO},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0},
      {"unknown", KEY_UNKNOWN},
      {(char*)0},
      {"euro", KEY_EURO},
      {(char*)0},
      {"a", KEY_A},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"i", KEY_I},
      {"context_menu", KEY_CONTEXT_MENU},
      {(char*)0}, {(char*)0},
      {"media", KEY_MEDIA},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"s", KEY_S},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"macro", KEY_MACRO},
      {"delete", KEY_DELETE},
      {(char*)0}, {(char*)0},
      {"send", KEY_SEND},
      {"deletefile", KEY_DELETEFILE},
      {"c", KEY_C},
      {(char*)0}, {(char*)0},
      {"data", KEY_DATA},
      {"comma", KEY_COMMA},
      {(char*)0},
      {"cd", KEY_CD},
      {(char*)0}, {(char*)0},
      {"macro30", KEY_MACRO30},
      {"l", KEY_L},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0},
      {"muhenkan", KEY_MUHENKAN},
      {(char*)0},
      {"minus", KEY_MINUS},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"database", KEY_DATABASE},
      {(char*)0},
      {"msdos", KEY_MSDOS},
      {(char*)0}, {(char*)0},
      {"dot", KEY_DOT},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"documents", KEY_DOCUMENTS},
      {"setup", KEY_SETUP},
      {(char*)0}, {(char*)0},
      {"esc", KEY_ESC},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"cut", KEY_CUT},
      {(char*)0}, {(char*)0},
      {"p", KEY_P},
      {"up", KEY_UP},
      {(char*)0}, {(char*)0},
      {"title", KEY_TITLE},
      {"camera_down", KEY_CAMERA_DOWN},
      {(char*)0},
      {"alterase", KEY_ALTERASE},
      {"time", KEY_TIME},
      {(char*)0},
      {"1", KEY_1},
      {(char*)0},
      {"linefeed", KEY_LINEFEED},
      {"calc", KEY_CALC},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"language", KEY_LANGUAGE},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"camera_zoomin", KEY_CAMERA_ZOOMIN},
      {(char*)0}, {(char*)0},
      {"numeric_0", KEY_NUMERIC_0},
      {(char*)0},
      {"iso", KEY_ISO},
      {(char*)0}, {(char*)0},
      {"camera", KEY_CAMERA},
      {"pc", KEY_PC},
      {"sat", KEY_SAT},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0},
      {"camera_access_enable", KEY_CAMERA_ACCESS_ENABLE},
      {"t", KEY_T},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"camera_access_toggle", KEY_CAMERA_ACCESS_TOGGLE},
      {(char*)0},
      {"camera_focus", KEY_CAMERA_FOCUS},
      {"numeric_d", KEY_NUMERIC_D},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"numeric_pound", KEY_NUMERIC_POUND},
      {"sos", KEY_SOS},
      {(char*)0},
      {"close", KEY_CLOSE},
      {(char*)0},
      {"ro", KEY_RO},
      {"numeric_a", KEY_NUMERIC_A},
      {(char*)0},
      {"enter", KEY_ENTER},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0},
      {"attendant_on", KEY_ATTENDANT_ON},
      {(char*)0},
      {"goto", KEY_GOTO},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"numeric_c", KEY_NUMERIC_C},
      {"camera_up", KEY_CAMERA_UP},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"redo", KEY_REDO},
      {"paste", KEY_PASTE},
      {"camera_access_disable", KEY_CAMERA_ACCESS_DISABLE},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"del_line", KEY_DEL_LINE},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"slowreverse", KEY_SLOWREVERSE},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"macro7", KEY_MACRO7},
      {"sendfile", KEY_SENDFILE},
      {"red", KEY_RED},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"numeric_1", KEY_NUMERIC_1},
      {"numeric_11", KEY_NUMERIC_11},
      {"radio", KEY_RADIO},
      {(char*)0},
      {"autopilot_engage_toggle", KEY_AUTOPILOT_ENGAGE_TOGGLE},
      {"mark_waypoint", KEY_MARK_WAYPOINT},
      {"info", KEY_INFO},
      {"scrolldown", KEY_SCROLLDOWN},
      {"cancel", KEY_CANCEL},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"camera_zoomout", KEY_CAMERA_ZOOMOUT},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0},
      {"macro8", KEY_MACRO8},
      {(char*)0}, {(char*)0},
      {"media_top_menu", KEY_MEDIA_TOP_MENU},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"root_menu", KEY_ROOT_MENU},
      {(char*)0},
      {"config", KEY_CONFIG},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"last", KEY_LAST},
      {"games", KEY_GAMES},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"list", KEY_LIST},
      {"tuner", KEY_TUNER},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"stop", KEY_STOP},
      {"sport", KEY_SPORT},
      {(char*)0},
      {"fn", KEY_FN},
      {"tape", KEY_TAPE},
      {"q", KEY_Q},
      {(char*)0},
      {"7", KEY_7},
      {"archive", KEY_ARCHIVE},
      {(char*)0},
      {"home", KEY_HOME},
      {"audio_desc", KEY_AUDIO_DESC},
      {"stopcd", KEY_STOPCD},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"ins_line", KEY_INS_LINE},
      {"vod", KEY_VOD},
      {(char*)0}, {(char*)0},
      {"record", KEY_RECORD},
      {(char*)0},
      {"numeric_7", KEY_NUMERIC_7},
      {"sat2", KEY_SAT2},
      {"volumedown", KEY_VOLUMEDOWN},
      {(char*)0}, {(char*)0},
      {"scrollup", KEY_SCROLLUP},
      {(char*)0}, {(char*)0},
      {"attendant_toggle", KEY_ATTENDANT_TOGGLE},
      {(char*)0},
      {"leftmeta", KEY_LEFTMETA},
      {(char*)0},
      {"video", KEY_VIDEO},
      {(char*)0}, {(char*)0},
      {"dvd", KEY_DVD},
      {"left_down", KEY_LEFT_DOWN},
      {"angle", KEY_ANGLE},
      {"camera_left", KEY_CAMERA_LEFT},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0},
      {"sidevu_sonar", KEY_SIDEVU_SONAR},
      {"numeric_8", KEY_NUMERIC_8},
      {(char*)0},
      {"sound", KEY_SOUND},
      {(char*)0}, {(char*)0},
      {"homepage", KEY_HOMEPAGE},
      {(char*)0}, {(char*)0},
      {"option", KEY_OPTION},
      {"left_up", KEY_LEFT_UP},
      {"calendar", KEY_CALENDAR},
      {(char*)0}, {(char*)0},
      {"8", KEY_8},
      {(char*)0},
      {"reserved", KEY_RESERVED},
      {"left", KEY_LEFT},
      {"hanja", KEY_HANJA},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"file", KEY_FILE},
      {(char*)0},
      {"r", KEY_R},
      {"onscreen_keyboard", KEY_ONSCREEN_KEYBOARD},
      {(char*)0},
      {"find", KEY_FIND},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"macro_preset_cycle", KEY_MACRO_PRESET_CYCLE},
      {"move", KEY_MOVE},
      {(char*)0}, {(char*)0},
      {"compose", KEY_COMPOSE},
      {"notification_center", KEY_NOTIFICATION_CENTER},
      {"open", KEY_OPEN},
      {(char*)0}, {(char*)0},
      {"media_repeat", KEY_MEDIA_REPEAT},
      {"macro_preset1", KEY_MACRO_PRESET1},
      {"help", KEY_HELP},
      {"props", KEY_PROPS},
      {"g", KEY_G},
      {(char*)0},
      {"volumeup", KEY_VOLUMEUP},
      {(char*)0},
      {"pause", KEY_PAUSE},
      {"numeric_star", KEY_NUMERIC_STAR},
      {"hangeul", KEY_HANGEUL},
      {"katakana", KEY_KATAKANA},
      {(char*)0},
      {"macro10", KEY_MACRO10},
      {"macro9", KEY_MACRO9},
      {(char*)0},
      {"numeric_2", KEY_NUMERIC_2},
      {"numeric_12", KEY_NUMERIC_12},
      {"email", KEY_EMAIL},
      {(char*)0},
      {"program", KEY_PROGRAM},
      {(char*)0},
      {"teen", KEY_TEEN},
      {(char*)0},
      {"macro3", KEY_MACRO3},
      {(char*)0}, {(char*)0},
      {"semicolon", KEY_SEMICOLON},
      {(char*)0},
      {"macro5", KEY_MACRO5},
      {"kpminus", KEY_KPMINUS},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"macro4", KEY_MACRO4},
      {"kpcomma", KEY_KPCOMMA},
      {(char*)0}, {(char*)0},
      {"prog1", KEY_PROG1},
      {(char*)0},
      {"10channelsdown", KEY_10CHANNELSDOWN},
      {"102nd", KEY_102ND},
      {(char*)0},
      {"scale", KEY_SCALE},
      {"spreadsheet", KEY_SPREADSHEET},
      {"hp", KEY_HP},
      {"displaytoggle", KEY_DISPLAYTOGGLE},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"save", KEY_SAVE},
      {(char*)0},
      {"kp0", KEY_KP0},
      {"suspend", KEY_SUSPEND},
      {"macro20", KEY_MACRO20},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"connect", KEY_CONNECT},
      {"yen", KEY_YEN},
      {"leftshift", KEY_LEFTSHIFT},
      {"phone", KEY_PHONE},
      {(char*)0},
      {"del_eos", KEY_DEL_EOS},
      {(char*)0}, {(char*)0},
      {"space", KEY_SPACE},
      {(char*)0},
      {"f1", KEY_F1},
      {"hiragana", KEY_HIRAGANA},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"del_eol", KEY_DEL_EOL},
      {(char*)0}, {(char*)0},
      {"kpdot", KEY_KPDOT},
      {"f10", KEY_F10},
      {"leftalt", KEY_LEFTALT},
      {"appselect", KEY_APPSELECT},
      {(char*)0},
      {"10channelsup", KEY_10CHANNELSUP},
      {"2", KEY_2},
      {(char*)0},
      {"numeric_9", KEY_NUMERIC_9},
      {(char*)0}, {(char*)0},
      {"macro1", KEY_MACRO1},
      {"macro11", KEY_MACRO11},
      {"numeric_3", KEY_NUMERIC_3},
      {(char*)0},
      {"sleep", KEY_SLEEP},
      {(char*)0}, {(char*)0},
      {"numeric_b", KEY_NUMERIC_B},
      {"shop", KEY_SHOP},
      {"first", KEY_FIRST},
      {"fastreverse", KEY_FASTREVERSE},
      {(char*)0}, {(char*)0},
      {"macro6", KEY_MACRO6},
      {(char*)0}, {(char*)0},
      {"controlpanel", KEY_CONTROLPANEL},
      {"numeric_4", KEY_NUMERIC_4},
      {"equal", KEY_EQUAL},
      {(char*)0}, {(char*)0},
      {"closecd", KEY_CLOSECD},
      {"numeric_5", KEY_NUMERIC_5},
      {"bookmarks", KEY_BOOKMARKS},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"tab", KEY_TAB},
      {"down", KEY_DOWN},
      {(char*)0}, {(char*)0},
      {"kprightparen", KEY_KPRIGHTPAREN},
      {"attendant_off", KEY_ATTENDANT_OFF},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"next_favorite", KEY_NEXT_FAVORITE},
      {"playpause", KEY_PLAYPAUSE},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"macro21", KEY_MACRO21},
      {(char*)0},
      {"emoji_picker", KEY_EMOJI_PICKER},
      {(char*)0},
      {"slow", KEY_SLOW},
      {"zoomout", KEY_ZOOMOUT},
      {(char*)0},
      {"camera_right", KEY_CAMERA_RIGHT},
      {(char*)0},
      {"news", KEY_NEWS},
      {"scrolllock", KEY_SCROLLLOCK},
      {"v", KEY_V},
      {"mhp", KEY_MHP},
      {(char*)0}, {(char*)0},
      {"wps_button", KEY_WPS_BUTTON},
      {(char*)0},
      {"zoomreset", KEY_ZOOMRESET},
      {(char*)0},
      {"next", KEY_NEXT},
      {(char*)0},
      {"playcd", KEY_PLAYCD},
      {(char*)0},
      {"apostrophe", KEY_APOSTROPHE},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"macro_preset2", KEY_MACRO_PRESET2},
      {(char*)0}, {(char*)0},
      {"k", KEY_K},
      {"macro17", KEY_MACRO17},
      {"single_range_radar", KEY_SINGLE_RANGE_RADAR},
      {(char*)0},
      {"als_toggle", KEY_ALS_TOGGLE},
      {(char*)0}, {(char*)0},
      {"vcr", KEY_VCR},
      {"rightmeta", KEY_RIGHTMETA},
      {"again", KEY_AGAIN},
      {"h", KEY_H},
      {"ok", KEY_OK},
      {(char*)0},
      {"nav_chart", KEY_NAV_CHART},
      {"micmute", KEY_MICMUTE},
      {"numeric_6", KEY_NUMERIC_6},
      {"numlock", KEY_NUMLOCK},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"next_element", KEY_NEXT_ELEMENT},
      {"epg", KEY_EPG},
      {"mail", KEY_MAIL},
      {"dictate", KEY_DICTATE},
      {"subtitle", KEY_SUBTITLE},
      {"macro_record_stop", KEY_MACRO_RECORD_STOP},
      {(char*)0},
      {"dollar", KEY_DOLLAR},
      {(char*)0},
      {"henkan", KEY_HENKAN},
      {"macro18", KEY_MACRO18},
      {"pvr", KEY_PVR},
      {(char*)0},
      {"prog2", KEY_PROG2},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"f", KEY_F},
      {(char*)0}, {(char*)0},
      {"messenger", KEY_MESSENGER},
      {"macro27", KEY_MACRO27},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"edit", KEY_EDIT},
      {"clear", KEY_CLEAR},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0},
      {"f7", KEY_F7},
      {(char*)0},
      {"vcr2", KEY_VCR2},
      {(char*)0},
      {"9", KEY_9},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"right", KEY_RIGHT},
      {"question", KEY_QUESTION},
      {(char*)0}, {(char*)0},
      {"stop_record", KEY_STOP_RECORD},
      {(char*)0},
      {"3", KEY_3},
      {"leftbrace", KEY_LEFTBRACE},
      {"macro_preset3", KEY_MACRO_PRESET3},
      {(char*)0},
      {"macro28", KEY_MACRO28},
      {"f20", KEY_F20},
      {(char*)0},
      {"macro_record_start", KEY_MACRO_RECORD_START},
      {(char*)0},
      {"video_next", KEY_VIDEO_NEXT},
      {"b", KEY_B},
      {"tv", KEY_TV},
      {(char*)0},
      {"text", KEY_TEXT},
      {(char*)0},
      {"full_screen", KEY_FULL_SCREEN},
      {"macro12", KEY_MACRO12},
      {(char*)0},
      {"select", KEY_SELECT},
      {(char*)0},
      {"katakanahiragana", KEY_KATAKANAHIRAGANA},
      {"pickup_phone", KEY_PICKUP_PHONE},
      {"copy", KEY_COPY},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"finance", KEY_FINANCE},
      {"clearvu_sonar", KEY_CLEARVU_SONAR},
      {(char*)0}, {(char*)0},
      {"4", KEY_4},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"logoff", KEY_LOGOFF},
      {"z", KEY_Z},
      {(char*)0},
      {"blue", KEY_BLUE},
      {"prog3", KEY_PROG3},
      {"5", KEY_5},
      {(char*)0},
      {"rightalt", KEY_RIGHTALT},
      {"back", KEY_BACK},
      {"front", KEY_FRONT},
      {"taskmanager", KEY_TASKMANAGER},
      {"f8", KEY_F8},
      {"nav_info", KEY_NAV_INFO},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"ab", KEY_AB},
      {(char*)0}, {(char*)0},
      {"prog4", KEY_PROG4},
      {(char*)0}, {(char*)0},
      {"kp1", KEY_KP1},
      {"macro2", KEY_MACRO2},
      {"macro22", KEY_MACRO22},
      {"w", KEY_W},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"channeldown", KEY_CHANNELDOWN},
      {"zenkakuhankaku", KEY_ZENKAKUHANKAKU},
      {(char*)0},
      {"zoomin", KEY_ZOOMIN},
      {"green", KEY_GREEN},
      {(char*)0},
      {"pausecd", KEY_PAUSECD},
      {"kp7", KEY_KP7},
      {(char*)0}, {(char*)0},
      {"keyboard", KEY_KEYBOARD},
      {(char*)0},
      {"f11", KEY_F11},
      {"insert", KEY_INSERT},
      {"screenlock", KEY_SCREENLOCK},
      {"rfkill", KEY_RFKILL},
      {"macro19", KEY_MACRO19},
      {"selective_screenshot", KEY_SELECTIVE_SCREENSHOT},
      {(char*)0},
      {"slash", KEY_SLASH},
      {"digits", KEY_DIGITS},
      {"macro13", KEY_MACRO13},
      {"uwb", KEY_UWB},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"shuffle", KEY_SHUFFLE},
      {(char*)0}, {(char*)0},
      {"forward", KEY_FORWARD},
      {"computer", KEY_COMPUTER},
      {(char*)0},
      {"f17", KEY_F17},
      {"wlan", KEY_WLAN},
      {"grave", KEY_GRAVE},
      {(char*)0},
      {"macro14", KEY_MACRO14},
      {"rotate_lock_toggle", KEY_ROTATE_LOCK_TOGGLE},
      {"sysrq", KEY_SYSRQ},
      {"right_down", KEY_RIGHT_DOWN},
      {"all_applications", KEY_ALL_APPLICATIONS},
      {"macro15", KEY_MACRO15},
      {(char*)0},
      {"rotate_display", KEY_ROTATE_DISPLAY},
      {"restart", KEY_RESTART},
      {"images", KEY_IMAGES},
      {"channel", KEY_CHANNEL},
      {"mp3", KEY_MP3},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"twen", KEY_TWEN},
      {"power", KEY_POWER},
      {"search", KEY_SEARCH},
      {"assistant", KEY_ASSISTANT},
      {(char*)0}, {(char*)0},
      {"macro29", KEY_MACRO29},
      {(char*)0},
      {"fn_e", KEY_FN_E},
      {"pagedown", KEY_PAGEDOWN},
      {"chat", KEY_CHAT},
      {"macro23", KEY_MACRO23},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"channelup", KEY_CHANNELUP},
      {(char*)0},
      {"rewind", KEY_REWIND},
      {"kpequal", KEY_KPEQUAL},
      {(char*)0},
      {"aspect_ratio", KEY_ASPECT_RATIO},
      {(char*)0}, {(char*)0},
      {"fn_d", KEY_FN_D},
      {(char*)0}, {(char*)0},
      {"macro24", KEY_MACRO24},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"backslash", KEY_BACKSLASH},
      {"macro25", KEY_MACRO25},
      {(char*)0},
      {"f2", KEY_F2},
      {(char*)0}, {(char*)0},
      {"kbd_layout_next", KEY_KBD_LAYOUT_NEXT},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0},
      {"fn_s", KEY_FN_S},
      {(char*)0},
      {"reply", KEY_REPLY},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"kbdillumup", KEY_KBDILLUMUP},
      {"leftctrl", KEY_LEFTCTRL},
      {"6", KEY_6},
      {(char*)0}, {(char*)0},
      {"macro16", KEY_MACRO16},
      {(char*)0}, {(char*)0},
      {"right_up", KEY_RIGHT_UP},
      {"voicemail", KEY_VOICEMAIL},
      {"video_prev", KEY_VIDEO_PREV},
      {"yellow", KEY_YELLOW},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"screensaver", KEY_SCREENSAVER},
      {(char*)0}, {(char*)0},
      {"forwardmail", KEY_FORWARDMAIL},
      {"videophone", KEY_VIDEOPHONE},
      {(char*)0},
      {"pause_record", KEY_PAUSE_RECORD},
      {(char*)0},
      {"vendor", KEY_VENDOR},
      {(char*)0},
      {"display_off", KEY_DISPLAY_OFF},
      {"fn_1", KEY_FN_1},
      {"fn_f1", KEY_FN_F1},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"hangup_phone", KEY_HANGUP_PHONE},
      {"new", KEY_NEW},
      {(char*)0},
      {"print", KEY_PRINT},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"buttonconfig", KEY_BUTTONCONFIG},
      {"macro26", KEY_MACRO26},
      {(char*)0}, {(char*)0},
      {"fastforward", KEY_FASTFORWARD},
      {"journal", KEY_JOURNAL},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"y", KEY_Y},
      {(char*)0},
      {"kp8", KEY_KP8},
      {"kpleftparen", KEY_KPLEFTPAREN},
      {"3d_mode", KEY_3D_MODE},
      {(char*)0}, {(char*)0},
      {"fishing_chart", KEY_FISHING_CHART},
      {(char*)0}, {(char*)0},
      {"touchpad_on", KEY_TOUCHPAD_ON},
      {"presentation", KEY_PRESENTATION},
      {"f21", KEY_F21},
      {"rightctrl", KEY_RIGHTCTRL},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"kpplus", KEY_KPPLUS},
      {(char*)0},
      {"kpenter", KEY_KPENTER},
      {(char*)0},
      {"backspace", KEY_BACKSPACE},
      {(char*)0}, {(char*)0},
      {"capslock", KEY_CAPSLOCK},
      {"f18", KEY_F18},
      {(char*)0},
      {"touchpad_toggle", KEY_TOUCHPAD_TOGGLE},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"play", KEY_PLAY},
      {(char*)0}, {(char*)0},
      {"brl_dot10", KEY_BRL_DOT10},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"favorites", KEY_FAVORITES},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"fn_f7", KEY_FN_F7},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"bassboost", KEY_BASSBOOST},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"cyclewindows", KEY_CYCLEWINDOWS},
      {"kp2", KEY_KP2},
      {(char*)0}, {(char*)0},
      {"kp6", KEY_KP6},
      {"f9", KEY_F9},
      {"lights_toggle", KEY_LIGHTS_TOGGLE},
      {(char*)0}, {(char*)0},
      {"j", KEY_J},
      {(char*)0},
      {"tv2", KEY_TV2},
      {(char*)0},
      {"kpplusminus", KEY_KPPLUSMINUS},
      {(char*)0},
      {"f3", KEY_F3},
      {"fn_f8", KEY_FN_F8},
      {(char*)0},
      {"rightshift", KEY_RIGHTSHIFT},
      {"x", KEY_X},
      {(char*)0},
      {"aux", KEY_AUX},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"fn_f10", KEY_FN_F10},
      {"f12", KEY_F12},
      {"kbdillumtoggle", KEY_KBDILLUMTOGGLE},
      {(char*)0},
      {"f16", KEY_F16},
      {(char*)0},
      {"radar_overlay", KEY_RADAR_OVERLAY},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"pageup", KEY_PAGEUP},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"addressbook", KEY_ADDRESSBOOK},
      {"f4", KEY_F4},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"brl_dot1", KEY_BRL_DOT1},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"f5", KEY_F5},
      {"previous", KEY_PREVIOUS},
      {(char*)0},
      {"switchvideomode", KEY_SWITCHVIDEOMODE},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"fn_2", KEY_FN_2},
      {"fn_f2", KEY_FN_F2},
      {"player", KEY_PLAYER},
      {"kpasterisk", KEY_KPASTERISK},
      {"wordprocessor", KEY_WORDPROCESSOR},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"wakeup", KEY_WAKEUP},
      {(char*)0},
      {"kbd_lcd_menu1", KEY_KBD_LCD_MENU1},
      {(char*)0},
      {"spellcheck", KEY_SPELLCHECK},
      {(char*)0}, {(char*)0},
      {"nextsong", KEY_NEXTSONG},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"refresh", KEY_REFRESH},
      {"kp3", KEY_KP3},
      {(char*)0},
      {"rightbrace", KEY_RIGHTBRACE},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"wwan", KEY_WWAN},
      {(char*)0}, {(char*)0},
      {"directory", KEY_DIRECTORY},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"kp9", KEY_KP9},
      {(char*)0},
      {"kp4", KEY_KP4},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"f13", KEY_F13},
      {"kpjpcomma", KEY_KPJPCOMMA},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"editor", KEY_EDITOR},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"brl_dot7", KEY_BRL_DOT7},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"fn_f", KEY_FN_F},
      {(char*)0},
      {"exit", KEY_EXIT},
      {(char*)0},
      {"f19", KEY_F19},
      {"frameforward", KEY_FRAMEFORWARD},
      {"f14", KEY_F14},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"kpslash", KEY_KPSLASH},
      {"fn_f9", KEY_FN_F9},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"fn_f3", KEY_FN_F3},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"fn_b", KEY_FN_B},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"voicecommand", KEY_VOICECOMMAND},
      {"brl_dot8", KEY_BRL_DOT8},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"kbdillumdown", KEY_KBDILLUMDOWN},
      {"fn_f4", KEY_FN_F4},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"fn_f5", KEY_FN_F5},
      {"fn_esc", KEY_FN_ESC},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"ejectcd", KEY_EJECTCD},
      {(char*)0},
      {"dual_range_radar", KEY_DUAL_RANGE_RADAR},
      {"break", KEY_BREAK},
      {"kp5", KEY_KP5},
      {(char*)0},
      {"f22", KEY_F22},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"f6", KEY_F6},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0},
      {"graphicseditor", KEY_GRAPHICSEDITOR},
      {(char*)0}, {(char*)0},
      {"f15", KEY_F15},
      {(char*)0},
      {"brl_dot2", KEY_BRL_DOT2},
      {(char*)0},
      {"battery", KEY_BATTERY},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0},
      {"previoussong", KEY_PREVIOUSSONG},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0},
      {"fn_f11", KEY_FN_F11},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0},
      {"fn_f6", KEY_FN_F6},
      {"fn_right_shift", KEY_FN_RIGHT_SHIFT},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"ejectclosecd", KEY_EJECTCLOSECD},
      {"kbd_lcd_menu2", KEY_KBD_LCD_MENU2},
      {"power2", KEY_POWER2},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"previous_element", KEY_PREVIOUS_ELEMENT},
      {(char*)0},
      {"f23", KEY_F23},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"brl_dot9", KEY_BRL_DOT9},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"brl_dot3", KEY_BRL_DOT3},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"f24", KEY_F24},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"brl_dot4", KEY_BRL_DOT4},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"brl_dot5", KEY_BRL_DOT5},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"kbd_lcd_menu3", KEY_KBD_LCD_MENU3},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0},
      {"kbdinputassist_nextgroup", KEY_KBDINPUTASSIST_NEXTGROUP},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"kbd_lcd_menu4", KEY_KBD_LCD_MENU4},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"kbd_lcd_menu5", KEY_KBD_LCD_MENU5},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"kbdinputassist_next", KEY_KBDINPUTASSIST_NEXT},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"xfer", KEY_XFER},
      {(char*)0},
      {"kbdinputassist_cancel", KEY_KBDINPUTASSIST_CANCEL},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"brl_dot6", KEY_BRL_DOT6},
      {(char*)0}, {(char*)0},
      {"bluetooth", KEY_BLUETOOTH},
      {(char*)0},
      {"kbdinputassist_accept", KEY_KBDINPUTASSIST_ACCEPT},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0},
      {"kbdinputassist_prevgroup", KEY_KBDINPUTASSIST_PREVGROUP},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0},
      {"privacy_screen_toggle", KEY_PRIVACY_SCREEN_TOGGLE},
      {"fn_f12", KEY_FN_F12},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"traditional_sonar", KEY_TRADITIONAL_SONAR},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"touchpad_off", KEY_TOUCHPAD_OFF},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"brightness_menu", KEY_BRIGHTNESS_MENU},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"brightness_min", KEY_BRIGHTNESS_MIN},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"brightness_auto", KEY_BRIGHTNESS_AUTO},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"brightnessdown", KEY_BRIGHTNESSDOWN},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"brightness_cycle", KEY_BRIGHTNESS_CYCLE},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"kbdinputassist_prev", KEY_KBDINPUTASSIST_PREV},
      {(char*)0}, {(char*)0}, {(char*)0},
      {"www", KEY_WWW},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0},
      {"brightnessup", KEY_BRIGHTNESSUP},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0},
      {"frameback", KEY_FRAMEBACK},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {(char*)0}, {(char*)0}, {(char*)0}, {(char*)0},
      {"brightness_max", KEY_BRIGHTNESS_MAX}
    };

  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register unsigned int key = hash_key_name (str, len);

      if (key <= MAX_HASH_VALUE)
        {
          register const char *s = wordlist[key].name;

          if (s && *str == *s && !strcmp (str + 1, s + 1))
            return &wordlist[key];
        }
    }
  return 0;
}
